### ISSUE TITLE
console.warn throwing error IE9

### ISSUE THREAD

**Issue by krismeister** [Jarlotee/ApplicationInsights-JS-Wrappers#1]
something around 
https://github.com/Jarlotee/ApplicationInsights-JS-Wrappers/blob/master/src/ts/wrappers/ConsoleWrapper.ts#L59
is breaking in IE9.

Test page:
https://betaqa.carmax.com/search#FreeText=Honda

![warnerror](https://cloud.githubusercontent.com/assets/1367719/12333617/3b629f9e-bac3-11e5-9fa7-d99763e7b297.png)

**Comment by Jarlotee** [comment]
Fixed, please update to applicationinsights-js-wrappers@0.1.1

**Comment by krismeister** [comment]
works like a champ thanks.

BTW I'm a big typescript fan.
